name: run ETL jobs

on:
  schedule:
    - cron: '*/5 * * * *'  # Schedule to run every 12 hours

jobs:
  run_docker_compose:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      APP_DB_USER: ${{ secrets.APP_DB_USER }}
      APP_DB_PASS: ${{ secrets.APP_DB_PASS }}
      APP_DB_NAME: ${{ secrets.APP_DB_NAME }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run Docker Compose
      run: |
        docker-compose -f JobsScraper/docker-compose.yml up
        docker-compose -f JobsScraper/docker-compose.yml wait jobmanager --down-project
