name: run_etl

on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_APP_DB_USER: ${{ secrets.APP_DB_USER }}
          envkey_APP_DB_PASS: ${{ secrets.APP_DB_PASS }}
          envkey_APP_DB_NAME: ${{ secrets.APP_DB_NAME }}
          directory: JobsScraper
          file_name: .env
      - name: docker compose act
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "JobsScraper/docker-compose.yml"
        env: 
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          APP_DB_USER: ${{ secrets.APP_DB_USER }}
          APP_DB_PASS: ${{ secrets.APP_DB_PASS }}
          APP_DB_NAME: ${{ secrets.APP_DB_NAME }}
      - name: Show Docker Compose logs
        run: docker-compose -f JobsScraper/docker-compose.yml logs
      
