name: run_etl

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Action
      - uses: wearerequired/lint-action@v2.3.0
      - name: Checkout code
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "JobsScraper/docker-compose.yml"
        env: 
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          APP_DB_USER: ${{ secrets.APP_DB_USER }}
          APP_DB_PASS: ${{ secrets.APP_DB_PASS }}
          APP_DB_NAME: ${{ secrets.APP_DB_NAME }}
