name: run_etl

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch .env
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres123" >> .env
          echo "POSTGRES_DB=postgres" >> .env
          echo "APP_DB_USER=data_wrangler_rw" >> .env
          echo "APP_DB_PASS=data_wrangler_rw123" >> .env
          echo "APP_DB_NAME=jobs_warehouse" >> .env
          cat .env
      - name: up postgres
        run: docker-compose -f JobsScraper/docker-compose.yml up postgresdb